### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by PanderMusubi** [scaljeri/scrummie#11]
Please improve README.md with a description (based on the text of the Pledgie campaign) and add screenshots with https://stackoverflow.com/questions/10189356/how-to-add-screenshot-to-readmes-in-github-repository

Possibly also an screencast in animated GIF can be included in too.

Fixing this issue will allow people to quickly understand what Scrummie is for before being submerged in technical details of installation et cetera as is now the case.

**Comment by PanderMusubi** [comment]
Also include in README the following link to image on Pledgie that shows progress of donation.

`<a href='https://pledgie.com/campaigns/25781'><img alt='Click here to lend your support to: Scrummie - first stable release of analogue digital Scrum board and make a donation at pledgie.com !' src='https://pledgie.com/campaigns/25781.png?skin_name=chrome' border='0' ></a>`

<a href='https://pledgie.com/campaigns/25781'><img alt='Click here to lend your support to: Scrummie - first stable release of analogue digital Scrum board and make a donation at pledgie.com !' src='https://pledgie.com/campaigns/25781.png?skin_name=chrome' border='0' ></a>

**Comment by scaljeri** [comment]
Done
