### ISSUE TITLE
Notify to HipChat

### ISSUE THREAD

**Issue by PanderMusubi** [scaljeri/scrummie#4]
As a scrum master I would like to add zero or more HipChat rooms to which notifications are being pushed when I am managing the configuration so that status changes of tasks can be notified to users.

Acceptation criteria:
- Zero or more HipChat rooms (each with an own API token) can be added, changed or removed in the configuration
- A notification will be send to all these contacts or conferences each time a task has been completed.
- The notification will be a short message in the format "[Task-type] task [task title] has been completed.", e.g. "Back-end task scrummie-123 refactoring has been completed.

See also https://github.com/jenkinsci/hipchat-plugin/blob/master/src/main/java/jenkins/plugins/hipchat/StandardHipChatService.java

**Comment by scaljeri** [comment]
Implemented. In scrummie.json a message can be defined which is shown when a task is moved to 'DONE'

```
"hipchat"  : {
      "message"    : "{{member.name}} finished task <a href='{{url}}/{{project}}/task/{{task._id}}'>{{task.title}}</a>",
      "active"     : true
  }
```
