### ISSUE TITLE
Possibility to add current username 

### ISSUE THREAD

**Issue by jvdieten** [scaljeri/scrummie#8]
Possibility to add current username. This will improve usability by:
- The taks created will be assigned to current user automatically  
- Task dragged to a different state will be assigned to current user automatically

**Comment by scaljeri** [comment]
This is possible now in two ways:

   1) Authenticate with Github; this way the application knows the current user and will automatically assign an un-assign task
   2) If Authentication is disabled, add the following search parameter to the url: ?member=john
